language: node_js

node_js:
  - "10"

script:
  - npm test

env:
  - CI=true

before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN -p ./build
  on:
    branch: master

notifications:
  email: false